Initial generation of config that will be loaded by xen.efi

diff --git a/uefi-mkconfig b/uefi-mkconfig
--- a/uefi-mkconfig
+++ b/uefi-mkconfig
@@ -54,7 +54,7 @@ prepare_initramfs () {
 		ewarn "Ignoring initramfs image \"$partition_mount$initramfs_image\" of \"$partition_mount$efi_file_path\""
 	elif [[ -f "$partition_mount$initramfs_image" ]]; then
 		# Check if corresponding initramfs exists
-		entry_kernel_commands="${config_kernel_commands} initrd=${initramfs_image//\//\\}"
+		[[ -z $XEN ]] && entry_kernel_commands="${entry_kernel_commands} initrd=${initramfs_image//\//\\}"
 	else
 		ewarn "No initramfs found for \"$partition_mount$efi_file_path\"."
 	fi
@@ -136,7 +136,7 @@ add_uefi_entry () {
 		if [[ $UMC_TEST == true ]]; then
 			echo "TEST: efibootmgr -q $opt_backup_efi -b \"$bootnum\" --disk \"/dev/$partition\" --part \"$partition_id\" --label \"$entry_label\" --loader \"${efi_loader}\" -u \"$entry_kernel_commands\""
 		else
-			efibootmgr -q $opt_backup_efi -b "$bootnum" --disk /dev/"$partition" --part "$partition_id" --label "$entry_label" --loader "${efi_loader}" -u "$entry_kernel_commands" || die "Failed to add UEFI ${msg_backup_efi}entry for \"$efi_file_path\""
+			efibootmgr -q $opt_backup_efi -b "$bootnum" --disk /dev/"$partition" --part "$partition_id" --label "$entry_label" --loader "${efi_loader}" -u ${entry_kernel_commands} || die "Failed to add UEFI ${msg_backup_efi}entry for \"$efi_file_path\""
 		fi
 	fi
 
@@ -145,11 +145,37 @@ add_uefi_entry () {
 add_xen_uefi_entry () {
 
 	local xen_efi_path
+	local xen_efi_files
+	local xen_config_files
+	
 	xen_efi_path=$( sed s/$efi_file_name//g <<< $efi_file_path )
-	echo "$xen_efi_path"
-	echo "$efi_file_name"
+	xen_efi_files=$( ls -w1 ${partition_mount}${xen_efi_path} | grep "xen" | grep ".efi" )
+	xen_config_files=$( ls -w1 ${partition_mount}${xen_efi_path} | grep "xen" | grep ".cfg" )
+		
+	prepare_initramfs
+
+	# Strip .uefibackup from efi file path
+	[[ "$efi_file_path" == *".uefibackup" ]] && efi_file_path=${efi_file_path//.uefibackup/}
+
+	prepare_shim
+	
+	prepare_microcode
+	
+	# Generate config which is loaded by Xen.efi
+	echo "global]
+default=$NAME
+
+[$NAME]
+options=${xen_options}
+kernel=$( echo ${efi_file_path} | sed "s/.*\///g")${entry_kernel_commands}
+ramdisk=$( echo ${initramfs_image} | sed "s/.*\///g")"
+
+	#efibootmgr -q ${opt_backup_efi} -b "${bootnum}" --disk /dev/"${partition}" --part "${partition_id}" --label "${entry_label}" --loader "${efi_loader}" -u ${xen_config_file}
 }
 
+#wipe_xen_configs () {
+#
+#}
 
 clean_legacy_entries () {
 	# Run only if no post 2.0 entries exist
@@ -487,9 +513,9 @@ main () {
 			# Convert chosen entry ID into hex
 			bootnum="$(printf %04X $bootnum)"
 			
-			entry_kernel_commands=""
+			entry_kernel_commands="${config_kernel_commands}"
 			
-			XEN=
+			XEN=1
 
 			if [[ -n $XEN ]]; then
 				add_xen_uefi_entry
