Fixing errors reported by shellcheck

diff --git a/uefi-mkconfig b/uefi-mkconfig
--- a/uefi-mkconfig
+++ b/uefi-mkconfig
@@ -1,4 +1,9 @@
 #!/usr/bin/env bash
+#TODO:
+#Rethink the ordering of added entries
+## Revers the order of added kernels
+## Revers the order of partition scanning
+#BUG: Recognising entries when firmware uppercased them is not working
 
 die() {
 	echo -e " ${NOCOLOR-\e[1;31m*\e[0m }${*}" >&2
@@ -47,19 +52,20 @@ add_uefi_entries () (
 		if ! check_if_uefi_entry_exists; then
 		
 			# Find first free hex address larger than or equal to 0100 for new UEFI boot entry
-			local bootnum=256 # 256 is decimal value of 0100
+			local bootnum
+			bootnum=256 # 256 is decimal value of 0100
 			while [[ "$(efibootmgr -u)" == *"Boot$(printf %04X $bootnum)"* ]]; do
-				local bootnum=$(($bootnum + 1))
+				bootnum=$((bootnum + 1))
 				
 				# Die if script exceeds managed range 0100-0200
-				if [[ $bootnum > 512 ]]; then
+				if [[ $bootnum -gt 512 ]]; then
 					die "All IDs, within managed range by uefi-mkconfig, are full!"
 				fi
 
 			done
 			
 			# Convert chosen entry ID into hex
-			local bootnum="$(printf %04X $bootnum)"
+			bootnum="$(printf %04X $bootnum)"
 
 			# Get kernel version
 			## Remove everything before /
@@ -71,8 +77,9 @@ add_uefi_entries () (
 				local kernel_version="${kernel_version/\.${kernel_version##*.}}"
 			fi
 
-			# Create label for UEFI entry
-			local partition_label="$(lsblk "/dev/$partition" -lno PARTLABEL)"
+			# Create label for UEFI eintry
+			local partition_label
+			partition_label="$(lsblk "/dev/$partition" -lno PARTLABEL)"
 			if [[ -n ${partition_label} ]]; then
 				local entry_label="$kernel_version-$partition_label"
 			else
@@ -83,7 +90,8 @@ add_uefi_entries () (
 			local initramfs_image="${efi_file_path/${efi_file_path##*/}}initramfs-$kernel_version.img"
 
 			# If shim is present in directory, presume it's used for every kernel in said directory
-			local shim="$(find $partition_mount${efi_file_path/${efi_file_path##*/}/} -maxdepth 1 -iname "*shim*.efi")"
+			local shim
+			shim="$(find "$partition_mount""${efi_file_path/${efi_file_path##*/}/}" -maxdepth 1 -iname "*shim*.efi")"
 			if [[ -n "$shim" ]]; then
 				local shim="${shim%%.efi*}.efi"
 				local adding_kernel_commands="${efi_file_path//\//\\} ${kernel_commands}"
@@ -102,7 +110,7 @@ add_uefi_entries () (
 			fi
 
 			# Add new entry
-			efibootmgr --create -b "$bootnum" --disk /dev/$partition --label "$entry_label" --loader "${efi_file_path//\//\\}" -u "$adding_kernel_commands" &>/dev/null || die "Failed to add UEFI entry for \"$efi_file_path\""
+			efibootmgr --create -b "$bootnum" --disk /dev/"$partition" --label "$entry_label" --loader "${efi_file_path//\//\\}" -u "$adding_kernel_commands" &>/dev/null || die "Failed to add UEFI entry for \"$efi_file_path\""
 			
 		else
 		
@@ -115,13 +123,13 @@ add_uefi_entries () (
 remove_uefi_entries () {
 
 	IFS=$'\n'		
-	for entry in $(efibootmgr -u | grep $partition_partuuid); do
+	for entry in $(efibootmgr -u | grep "$partition_partuuid"); do
 
 		# Get Hex number of a entry
 		local uefi_entry_hex="${entry:4:4}"
 		
 		# Check if the entry is within range managed by uefi-mkconfig
-		if [[ $((16#$uefi_entry_hex)) > 255 ]] && [[ $((16#$uefi_entry_hex)) < 513 ]]; then
+		if [[ $((16#$uefi_entry_hex)) -gt 255 ]] && [[ $((16#$uefi_entry_hex)) -lt 513 ]]; then
 		
 			# Get Entry kernel commands
 			## Remove everything before last ) so only kernel commands remain
@@ -151,14 +159,14 @@ remove_uefi_entries () {
 				
 				# Delete entry
 				ewarn "Deleting UEFI entry \"$uefi_entry_hex\"! Its EFI file \"$partition_mount${entry_efi_path//\\/\/}\" wasn't found."
-				efibootmgr -q -B -b $uefi_entry_hex || die "Failed to delete entry \"$uefi_entry_hex\""
+				efibootmgr -q -B -b "$uefi_entry_hex" || die "Failed to delete entry \"$uefi_entry_hex\""
 			
 			# Delete entry if kernel commands are not the same as in config file. Don't do this if kernel commands are taken from /proc/cmdline
-			elif [[ "$kernel_commands" != "$entry_kernel_commands" ]] && [[ $proc_kernel_commands == False ]]; then
+			elif [[ "$kernel_commands" != "$entry_kernel_commands" ]] && [[ -z $proc_kernel_commands ]]; then
 				
 				# Delete entry for regeneration
 				ewarn "Deleting UEFI entry \"$uefi_entry_hex\" for regeneration! Kernel commads in configuration differ from the ones in this entry."
-				efibootmgr -q -B -b $uefi_entry_hex || die "Failed to delete entry \"$uefi_entry_hex\""
+				efibootmgr -q -B -b "$uefi_entry_hex" || die "Failed to delete entry \"$uefi_entry_hex\""
 	
 			fi
 	
@@ -171,7 +179,7 @@ remove_uefi_entries () {
 main () {
 	efi_parttype="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
 	mounted_efi_partitions=$(lsblk -lo NAME,MOUNTPOINTS,PARTTYPE | grep  "$efi_parttype" | grep "/" | cut -d' ' -f1)
-	proc_kernel_commands=False
+	proc_kernel_commands=
 	
 	einfo "Running uefi-mkconfig..."
 
@@ -194,7 +202,7 @@ main () {
 		kernel_commands="$(tr -s "${IFS}" ' ' </usr/lib/kernel/uefi-mkconfig)"
 	else
 		kernel_commands="$(tr -s "${IFS}" '\n' </proc/cmdline | grep -ve '^BOOT_IMAGE=' -e '^initrd=' | tr '\n' ' ')"
-		proc_kernel_commands=True
+		proc_kernel_commands=1
 	fi
 
 	# Strip initrd=* from config file
@@ -212,10 +220,10 @@ main () {
 
 		# Find where disk is mounted
 		# Head at the end deals with cases where this partition is mounted in multiple places
-		partition_mount=$(lsblk "/dev/$partition" -lno MOUNTPOINTS | head -n 1)
+		partition_mount=$(lsblk /dev/"$partition" -lno MOUNTPOINTS | head -n 1)
 
 		# Find all .efi files on this partition
-		partition_efis="$(find $partition_mount \( -name "vmlinuz-*.efi" -o -name "vmlinux-*.efi" -o -name "gentoo-*.efi" -o -name "kernel-*.efi" -o -name "bzImage*.efi" -o -name "zImage*.efi" -o -name "vmlinuz.efi" \))"
+		partition_efis="$(find "$partition_mount" \( -name "vmlinuz-*.efi" -o -name "vmlinux-*.efi" -o -name "gentoo-*.efi" -o -name "kernel-*.efi" -o -name "bzImage*.efi" -o -name "zImage*.efi" -o -name "vmlinuz.efi" \))"
 		
 		# Remove invalid entries
 		remove_uefi_entries
