Some more refactoring

diff --git a/uefi-mkconfig b/uefi-mkconfig
--- a/uefi-mkconfig
+++ b/uefi-mkconfig
@@ -44,7 +44,8 @@ add_uefi_entries () (
 	for efi_file in $partition_efis; do
 		
 		# Prepare path which will be inserted into efibootmgr
-		local efi_file_path="${efi_file//$partition_mount}"
+		local efi_file_path
+		efi_file_path="${efi_file//$partition_mount}"
 
 		# Add entry if it doesn't exist
 		if ! check_if_uefi_entry_exists; then
@@ -67,51 +68,55 @@ add_uefi_entries () (
 
 			# Get kernel version
 			## Remove everything before /
-			local kernel_version="${efi_file_path//*\//}"
+			local kernel_version
+			kernel_version="${efi_file_path//*\//}"
 			## Remove everything before first - to remove any prefixes
-			local kernel_version="${kernel_version/${kernel_version%%-*}-/}"
+			kernel_version="${kernel_version/${kernel_version%%-*}-/}"
 			## Remove .efi suffix if it exists
 			if [[ "$kernel_version" == *".efi"* ]]; then
-				local kernel_version="${kernel_version/\.${kernel_version##*.}}"
+				kernel_version="${kernel_version/\.${kernel_version##*.}}"
 			fi
 
 			# Create label for UEFI eintry
 			local partition_label
+			local entry_label
 			partition_label="$(lsblk "/dev/$partition" -lno PARTLABEL)"
 			if [[ -n ${partition_label} ]]; then
-				local entry_label="$kernel_version-$partition_label"
+				entry_label="$kernel_version-$partition_label"
 			else
-				local entry_label="$kernel_version"
+				entry_label="$kernel_version"
 			fi
 			
 			# Create path to initramfs
-			local initramfs_image="${efi_file_path/${efi_file_path##*/}}initramfs-$kernel_version.img"
-
-			# Add .old suffix to initramfs in case we are handling kernel with -old suffix
+			local initramfs_image
+			initramfs_image="${efi_file_path/${efi_file_path##*/}}initramfs-$kernel_version.img"
+			## Add .old suffix to initramfs in case we are handling kernel with -old suffix
 			[[ "$efi_file_path" == *"-old."* ]] && initramfs_image="${initramfs_image/-old}.old"
 
 			# If shim is present in directory, presume it's used for every kernel in said directory
 			local shim
+			local adding_kernel_commands
 			shim="$(find "$partition_mount""${efi_file_path/${efi_file_path##*/}/}" -maxdepth 1 -iname "*shim*.efi")"
 			if [[ -n "$shim" ]]; then
-				local shim="${shim%%.efi*}.efi"
-				local adding_kernel_commands="${efi_file_path//\//\\} ${kernel_commands}"
+				shim="${shim%%.efi*}.efi"
+				adding_kernel_commands="${efi_file_path//\//\\} ${kernel_commands}"
 				ewarn "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" using shim \"$shim\" found on \"$partition\"..."
-				local efi_file_path="${efi_file_path/${efi_file_path##*/}/}${shim/*\//}"
+				efi_file_path="${efi_file_path/${efi_file_path##*/}/}${shim/*\//}"
 			else
-				local adding_kernel_commands="${kernel_commands}"
+				adding_kernel_commands="${kernel_commands}"
 				ewarn "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" found on \"$partition\"..."
 			fi
 
 			# Check if corresponding initramfs exists
 			if [[ -f "$partition_mount$initramfs_image" ]]; then
-				local adding_kernel_commands="${adding_kernel_commands} initrd=${initramfs_image//\//\\}"
+				adding_kernel_commands="${adding_kernel_commands} initrd=${initramfs_image//\//\\}"
 			else
 				ewarn "No initramfs found for \"$partition_mount$efi_file_path\"."
 			fi
 
 			# Add new entry
-			efibootmgr --create -b "$bootnum" --disk /dev/"$partition" --label "$entry_label" --loader "${efi_file_path//\//\\}" -u "$adding_kernel_commands" &>/dev/null || die "Failed to add UEFI entry for \"$efi_file_path\""
+			efibootmgr --create -b "$bootnum" --disk /dev/"$partition" --label "$entry_label" --loader "${efi_file_path//\//\\}"\
+			-u "$adding_kernel_commands" &>/dev/null || die "Failed to add UEFI entry for \"$efi_file_path\""
 			
 		else
 		
@@ -127,39 +132,40 @@ remove_uefi_entries () {
 	for entry in $(efibootmgr -u | grep "$partition_partuuid"); do
 
 		# Get Hex number of a entry
-		local uefi_entry_hex="${entry:4:4}"
+		local uefi_entry_hex
+		uefi_entry_hex="${entry:4:4}"
 		
 		# Check if the entry is within range managed by uefi-mkconfig
 		if [[ $((16#$uefi_entry_hex)) -gt 255 ]] && [[ $((16#$uefi_entry_hex)) -lt 513 ]]; then
-		
-			# Get Entry kernel commands
-			## Remove everything before last ) so only kernel commands remain
+
+			local entry_efi_path
+			local entry_kernel_commands
 
 			# Create path to efi file
 			## Decide if entry is shim entry or not
 			if [[ "$entry" ==  *"File("*"shim"*")"* ]] || [[ "$entry" ==  *"File("*"SHIM"*")"* ]]; then
 				### Remove everything after and included with last character )
 				#echo $entry
-				local entry_efi_path="${entry##*(\.}"
+				entry_efi_path="${entry##*(\.}"
 				### Remove everything after and included with last space
-				local entry_efi_path="${entry_efi_path%%\ *}"
+				entry_efi_path="${entry_efi_path%%\ *}"
 				
 				### Prepare Entry kernel commands in case of shim booting
-				local entry_kernel_commands=${entry##*\.efi}
-				local entry_kernel_commands=${entry_kernel_commands//)*}
-				local entry_kernel_commands=${entry_kernel_commands/#\ }
+				entry_kernel_commands=${entry##*\.efi}
+				entry_kernel_commands=${entry_kernel_commands//)*}
+				entry_kernel_commands=${entry_kernel_commands/#\ }
 			else
 				### Remove everything before first mention of string File(
-				local entry_efi_path="${entry/${entry%%File(*}File\(/}"
+				entry_efi_path="${entry/${entry%%File(*}File\(/}"
 				### Remove everything after first ) character
-				local entry_efi_path="${entry_efi_path%%)*}"
+				entry_efi_path="${entry_efi_path%%)*}"
 
 				### Prepare Entry kernel commands
-				local entry_kernel_commands=${entry/#*\.efi)}
+				entry_kernel_commands=${entry/#*\.efi)}
 			fi
 			
 			# Remove initramfs entry from the kernel commands
-			local entry_kernel_commands=${entry_kernel_commands// initrd*}
+			entry_kernel_commands=${entry_kernel_commands// initrd*}
 	
 			# Check if efi file exists and if this entry in in managed range	
 			if [ ! -f "$partition_mount${entry_efi_path//\\/\/}" ]; then
@@ -230,7 +236,8 @@ main () {
 		partition_mount=$(lsblk /dev/"$partition" -lno MOUNTPOINTS | head -n 1)
 
 		# Find all .efi files on this partition
-		partition_efis="$(find "$partition_mount" \( -name "vmlinuz-*.efi" -o -name "vmlinux-*.efi" -o -name "gentoo-*.efi" -o -name "kernel-*.efi" -o -name "bzImage*.efi" -o -name "zImage*.efi" -o -name "vmlinuz.efi" \) | sort -r)"
+		partition_efis="$(find "$partition_mount" \( -name "vmlinuz-*.efi" -o -name "vmlinux-*.efi" -o -name "gentoo-*.efi"\
+		-o -name "kernel-*.efi" -o -name "bzImage*.efi" -o -name "zImage*.efi" -o -name "vmlinuz.efi" \) | sort -r)"
 		
 		# Remove invalid entries
 		remove_uefi_entries
