Fixing issues pointed out by Andrew plus some more refactoring

diff --git a/uefi-mkconfig b/uefi-mkconfig
--- a/uefi-mkconfig
+++ b/uefi-mkconfig
@@ -15,16 +15,11 @@ ewarn() {
 
 add_uefi_entry () (
 
-	# Create label for UEFI eintry
+	# Create label for UEFI entry
 	local entry_label
-	if [[ -n ${partition_label} ]]; then
-		entry_label="$kernel_version on $partition_label "
-	else
-		# If no partition label exists, add partition mount instead
-		entry_label="$kernel_version in ${partition_mount/\/} "
-	fi
+	entry_label="$kernel_version on $partition_label "
 
-	# Add prefix to entry label for better identification
+	# Add prefix to entry label for easier identification
 	if [[ -n $backup_efi ]]; then
 		entry_label="UMCB $entry_label"
 	else
@@ -37,6 +32,9 @@ add_uefi_entry () (
 	## Add .old suffix to initramfs in case we are handling kernel with -old suffix
 	[[ "$efi_file_path" == *"-old."* ]] && initramfs_image="${initramfs_image/-old}.old"
 
+	# Strip .uefibackup from efi file path
+	[[ "$efi_file_path" == *".uefibackup" ]] && efi_file_path=${efi_file_path//.uefibackup/}
+
 	# If shim is present in directory, presume it's used for every kernel in said directory
 	local shim
 	local adding_kernel_commands
@@ -44,14 +42,19 @@ add_uefi_entry () (
 	if [[ -n "$shim" ]]; then
 		shim="${shim%%.efi*}.efi"
 		adding_kernel_commands="${efi_file_path//\//\\} ${kernel_commands}"
-		einfo "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" using shim \"$shim\" found on \"$partition\"..."
+		if [[ -n $backup_efi ]]; then
+			einfo "Creating BACKUP UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" using shim \"$shim\" found on \"$partition\""
+		else
+			einfo "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" using shim \"$shim\" found on \"$partition\""
+		fi
 		efi_file_path="${efi_file_path/${efi_file_path##*/}/}${shim/*\//}"
-	elif [[ -n $backup_efi ]]; then
-		adding_kernel_commands="${kernel_commands}"
-		einfo "Creating BACKUP UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" found on \"$partition\"..."	
 	else
 		adding_kernel_commands="${kernel_commands}"
-		einfo "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" found on \"$partition\"..."
+		if [[ -n $backup_efi ]]; then
+			einfo "Creating BACKUP UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" found on \"$partition\""		
+		else
+			einfo "Creating UEFI entry \"$bootnum\" for \"$partition_mount$efi_file_path\" found on \"$partition\""
+		fi
 	fi
 			
 	# Check if microcode image exists
@@ -76,7 +79,7 @@ add_uefi_entry () (
 	if [[ -n $backup_efi ]]; then
 		# When creating backup entry, don't add it to the bootorder
 		efibootmgr -q --create-only -b "$bootnum" --disk /dev/"$partition" --label "$entry_label" --loader "${efi_file_path//\//\\}"\
-			-u "$adding_kernel_commands" || die "Failed to add UEFI entry for \"$efi_file_path\""
+			-u "$adding_kernel_commands" || die "Failed to add BACKUP UEFI entry for \"$efi_file_path\""
 	else
 		efibootmgr -q --create -b "$bootnum" --disk /dev/"$partition" --label "$entry_label" --loader "${efi_file_path//\//\\}"\
 			-u "$adding_kernel_commands" || die "Failed to add UEFI entry for \"$efi_file_path\""
@@ -85,10 +88,11 @@ add_uefi_entry () (
 
 wipe_entries () {
 	local initial_uefi_umc_state
+
+	# Get list of all non backup entries made by uefi-mkconfig
 	initial_uefi_umc_state="$(printf %s "$initial_uefi_state" | grep " UMC ")"
 	
 	local IFS=$'\n'
-	
 	for delete_entry in $initial_uefi_umc_state; do
 		efibootmgr -q -B -b "${delete_entry:4:4}"
 	done
@@ -96,7 +100,7 @@ wipe_entries () {
 
 main () {
 	efi_parttype="c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
-	mounted_efi_partitions=$(lsblk -lo NAME,MOUNTPOINTS,PARTTYPE | grep  "$efi_parttype" | grep "/" | cut -d' ' -f1 | sort -r)
+	mounted_efi_partitions=$(lsblk -lno MOUNTPOINTS,PARTTYPE | grep "$efi_parttype")
 	valid_kernel_commands=
 	kernel_prefixes="vmlinuz vmlinux- kernel- bzImage zImage"
 	
@@ -111,7 +115,7 @@ main () {
 	elif [[ -z ${mounted_efi_partitions} ]]; then
 		die "No mounted efi partitions!"
 
-	elif [[ -z "$(command -v efibootmgr)" ]]; then
+	elif [[ ! -x "$(which efibootmgr)" ]]; then
 		die "efibootmgr dependency not found!"
 
 	fi
@@ -153,12 +157,10 @@ main () {
 
 	# Verify kernel commands
         for check_config in $kernel_commands; do
-
                 # Strip initrd=* from config file
                 [[ "$check_config" != *"initrd="* ]] && strip_kernel_commands="$strip_kernel_commands $check_config"
                 # Verify if "root=" is present
                 [[ "$check_config" == "root="* ]] && valid_kernel_commands=1
-
         done
 	kernel_commands="$strip_kernel_commands"
 
@@ -170,33 +172,18 @@ main () {
 	# Wipe all managed entries for regeneration
 	wipe_entries
 	
-	for partition in $mounted_efi_partitions; do
+	partition_mounts="${mounted_efi_partitions// "$efi_parttype"/}"
+	
+	# Find all .efi files on this partition and split them to old and new
+	for prefix in $kernel_prefixes; do
+		find_results_new="$(find $partition_mounts -name "$prefix*.efi" ! -name "$prefix*-old.efi" -printf "%f\n")"
+		find_results_old="$(find $partition_mounts -name "$prefix*-old.efi" -printf "%f\n")"
+		[[ -n "$find_results_new" ]] && kernel_images_new+="$find_results_new "
+		[[ -n "$find_results_old" ]] && kernel_images_old+="$find_results_old "
+	done
 
-		# Find where disk is mounted
-		# Head at the end deals with cases where this partition is mounted in multiple places
-		partition_mount=$(lsblk /dev/"$partition" -lno MOUNTPOINTS | head -n 1)
-		if [[ -z $partition_mounts ]]; then
-			partition_mounts="$partition_mount"
-		else
-			partition_mounts="$partition_mounts $partition_mount"
-		fi
-
-		# Reset variables
-		local kernel_images_new=
-		local kernel_images_old=
-
-		# Find all .efi files on this partition and split them to old and new
-		for prefix in $kernel_prefixes; do
-			find_results_new="$(find "$partition_mount" -name "$prefix*.efi" ! -name "$prefix*-old.efi" -printf "%f\n")"
-			find_results_old="$(find "$partition_mount" -name "$prefix*-old.efi" -printf "%f\n")"
-			[[ -n "$find_results_new" ]] && kernel_images_new+="$find_results_new "
-			[[ -n "$find_results_old" ]] && kernel_images_old+="$find_results_old "
-		done
-
-		# Sort kernel images
-		kernel_images="$(sort -uV <<< "$kernel_images_old") $(sort -uV <<< "$kernel_images_new")"
-
-	done 
+	# Sort kernel images
+	kernel_images="$(sort -uV <<< "$kernel_images_old") $(sort -uV <<< "$kernel_images_new")"
 
 	# Add path back to the kernel image
 	for kernel_image in $kernel_images; do
@@ -206,13 +193,11 @@ main () {
 	
 	# Move backup entries to the beginning of the list
 	for efi_file in $partition_efis; do
-		if [[ -f "${efi_file}.uefibackup" ]]; then
-			partition_efis="${efi_file}.uefibackup ${partition_efis}"
-		fi
+		[[ -f "${efi_file}.uefibackup" ]] && partition_efis="${efi_file}.uefibackup ${partition_efis}"
 	done
 	
 	for efi_file in $partition_efis; do
-		# Skip this kernel if ignore file is found
+		# Skip this kernel version if ignore file is found
 		if [[ -f "$efi_file.ignore" ]]; then
 			ewarn "Ignoring \"$efi_file\" from partition \"$partition\"."
 			continue
@@ -228,7 +213,9 @@ main () {
 		
 		# Get partition label
 		partition_label="$(lsblk "/dev/$partition" -lno PARTLABEL)"
-
+		## In case PARTLABEL isn't set, use UUID
+		[[ -z "$partition_label" ]] && partition_label="$(lsblk "/dev/$partition" -lno UUID)"
+		
 		# Prepare path which will be inserted into efibootmgr
 		efi_file_path="${efi_file//$partition_mount}"
 
@@ -238,23 +225,19 @@ main () {
 		## Remove everything before first - to remove any prefixes
 		kernel_version="${kernel_version/${kernel_version%%-*}-/}"
 		## Remove .efi suffix if it exists
-		if [[ "$kernel_version" == *".efi"* ]]; then
-			kernel_version="${kernel_version/.efi*/}"
-		fi
+		[[ "$kernel_version" == *".efi"* ]] && kernel_version="${kernel_version/.efi*/}"
 			
+		backup_efi=
+		local backup_entry
 		# Check for existence of backup entry
 		if [[ "$efi_file" == *".uefibackup" ]]; then
-			if [[ "$initial_uefi_state" == *"UMCB ${kernel_version} on ${partition_label} "* ]]; then
-				einfo "Found already existing backup in ${partition}"
-				continue
-			elif [[ "$initial_uefi_state" == *"UMCB ${kernel_version} in ${partition_mount/\//} "* ]]; then
-				einfo "Found already existing backup in ${partition}"
+			efi_file="${efi_file/.uefibackup/}"
+			backup_entry="$(grep "UMCB ${kernel_version} on ${partition_label} " <<< "$initial_uefi_state")"
+			if [[ -n "$backup_entry" ]]; then
+				einfo "Existing BACKUP UEFI entry \"${backup_entry:4:4}\" for \"${efi_file}\" found on \"${partition}\""
 				continue
 			fi
-			backup_efi=0
-			efi_file="${efi_file/.uefibackup/}"
-		else
-			backup_efi=
+			backup_efi=1
 		fi
 
 		# If bootnum is empty, set it to max ID 0200
@@ -268,12 +251,8 @@ main () {
 		# Find first free hex address smaller than or equal to 0200 for new UEFI boot entry
 		while [[ "$(grep -v " UMC " <<< "$initial_uefi_state")" == *"Boot$(printf %04X $bootnum)"* ]]; do
 			bootnum=$((bootnum - 1))
-			
 			# Die if script exceeds managed range 0200-0100
-			if [[ $bootnum -lt 256 ]]; then
-				die "All IDs, within managed range by uefi-mkconfig, are full!"
-			fi
-
+			[[ $bootnum -lt 256 ]] && die "All Boot IDs within managed range are taken!"
 		done
 
 		# Convert chosen entry ID into hex
